title: CV | Sara Ynes Gonzales Santisteban
description:  Sara Ynes Gonzales Santisteban's CV based on jekyll template by Stavrospanakakis
url: https://saraynesgs.github.io/cv-saraynesgs/
baseurl: ''
theme_skin: blue

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-minifier

exclude:
  - docker-compose.yml
